version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  add-api:
    build: .
    image: add-api
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - MONGO_URL=mongodb://mongo:27017/add-api-local